<div class="row">
    <?php
    if (!empty($users)) {
        ?>
        <div class="col-md-1">#</div>
        <div class="col-md-4">Email</div>
        <div class="col-md-4">First Name</div>
        <div class="col-md-3">Last Name</div>
        <?php
        $sm = $this->getHelperPluginManager()->getServiceLocator();
        $counter = 1;
        $escaper = new Zend\Escaper\Escaper('utf-8');
        foreach ($users as $userKey => $user) {
            ?>
            <div class="col-md-1">
                <?php
                echo $counter;
                ?>
            </div>
            <div class="col-md-4">
                <?php
                echo $escaper->escapeHtml($user->getEmail());
                ?>
            </div>
            <?php
            ?>
            <div class="col-md-4">
                <?php
                echo $escaper->escapeHtml($user->getFirstName());
                ?>
            </div>
            <div class="col-md-3">
                <?php
                echo $escaper->escapeHtml($user->getLasttName());
                ?>
            </div>
        <?php
            $counter++;
        }
        ?>
        </div>
        <?php
    }
    ?>
<form action="/sync" method="POST">
    <button type="submit">Synchronize</button>
</form>
</div>
