
    <?php
    $flash = $this->flashMessenger();
    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
    if (!empty($users)) {
        ?>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Email</th>
                <th>First Name</th>
                <th>Last Name</th>
            </tr>
        </thead>
        <tbody>
        <?php
        $sm = $this->getHelperPluginManager()->getServiceLocator();
        $counter = 1;
        $escaper = new Zend\Escaper\Escaper('utf-8');
        foreach ($users as $userKey => $user) {
            ?>

            <tr>
                <th scope="row">
                    <?php
                    echo $counter;
                    ?>
                </th>
            <td>
                <?php
                echo $escaper->escapeHtml($user->getEmail());
                ?>
            </td>
            <?php
            ?>
            <td>
                <?php
                echo $escaper->escapeHtml($user->getFirstName());
                ?>
            </td>
            <td>
                <?php
                echo $escaper->escapeHtml($user->getLastName());
                ?>
            </td>
        <?php
            $counter++;
        }
        ?>
        </tbody>
        <?php
    }
    ?>
    </table>
<form action="/sync" method="POST">
    <button type="submit" class="btn-primary">Synchronize</button>
</form>

